-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 10:46:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prism` DEFAULT CHARACTER SET utf8mb4 ;
USE `prism` ;

-- -----------------------------------------------------
-- Table `prism`.`prism_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prism`.`prism_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` TINYINT UNSIGNED NOT NULL,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `uid` BIGINT UNSIGNED NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `context` VARCHAR(50) NOT NULL DEFAULT '',
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prism`.`prism_rec_interact_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prism`.`prism_rec_interact_word` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `uid` BIGINT UNSIGNED NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `INDEX_UID` (`uid` ASC) VISIBLE,
  INDEX `INDEX_ROOM_ID` (`room_id` ASC) VISIBLE,
  INDEX `UN_R_U` (`room_id` ASC, `uid` ASC) INVISIBLE,
  INDEX `INDEX_TYPE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prism`.`prism_rec_danmu_body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prism`.`prism_rec_danmu_body` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `uid` BIGINT UNSIGNED NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `INDEX_UID` (`uid` ASC) INVISIBLE,
  INDEX `INDEX_ROOM_ID` (`room_id` ASC) VISIBLE,
  INDEX `UN_R_U` (`room_id` ASC, `uid` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prism`.`prism_rec_send_gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prism`.`prism_rec_send_gift` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `uid` BIGINT UNSIGNED NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `gift_id` BIGINT UNSIGNED NOT NULL,
  `gift_name` VARCHAR(10) NOT NULL,
  `num` INT UNSIGNED NOT NULL,
  `coin_type` VARCHAR(16) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `discount_price` INT NOT NULL,
  `total_coin` INT NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `INDEX_UID` (`uid` ASC) INVISIBLE,
  INDEX `INDEX_ROOM_ID` (`room_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
